# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy dependency list and install packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install uv

# Copy the rest of the application code
COPY . .

# Expose any needed ports (if applicable)
EXPOSE 8000

# Start the MCP server using uv and fastmcp
CMD ["uv", "run", "--with", "fastmcp", "fastmcp", "run", "server.py"]
